# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: webapp
        POSTGRES_PASSWORD: summer@.2023
        POSTGRES_DB: postgres
