import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import { ToastProvider } from '@/components/providers/toast-privider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '博泰移民-专注加拿大移民15年',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={ inter.className }>
      <ToastProvider/>
      { children }
      </body>
      </html>
  )
}
